modLoader="javafml" #mandatory
loaderVersion="[44,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/Travelers-Titles"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_full_name}"
    credits="Thanks so much to all my patrons!"
    authors="YUNGNICKYOUNG"
    description="${mod_description}"
    logoFile="icon.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/travelers-titles"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[44.1.0,)"

[[dependencies.${mod_id}]]
    modId="yungsapi"
    versionRange="[${minecraft_version}-Forge-${yungsapi_version},)"
    mandatory=true
    ordering="NONE"
    side="BOTH"