modLoader="javafml"
loaderVersion="[35,)"
license="GPLv3"
issueTrackerURL="https://github.com/yungnickyoung/Travelers_Titles/issues"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
credits="${modCredits}"
authors="${modAuthor}"
description="${modDescription}"
logoFile="logo.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/travelers-titles"

[[dependencies.travelerstitles]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="CLIENT"

[[dependencies.travelerstitles]]
modId="yungsapi"
versionRange="[1.16.4-Forge-11,)"
mandatory=true
ordering="NONE"
side="CLIENT"